# Generated by Django 4.2.13 on 2025-02-25 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articulos', '0001_initial'),
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='tipo_mascota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mascotas.tipomascota'),
        ),
    ]
